export interface UserStory {
  id: string; // e.g., "1.1"
  epic: string; // e.g., "EPIC 1: User Authentication and Account Management"
  fullTitleHeader: string; // e.g., "User Story 1.1: User Registration" or "User Story 1.1"
  specificTitle: string; // e.g., "Implement user registration functionality"
  description: string;
  acceptanceCriteria: string[];
  estimation: number | null;
  image: string | null; // e.g., "/file-name.png"
  isBacklog: boolean;
  rawContent: string; // Store the raw block for searching
}

export const userStories: UserStory[] = [
  {
    id: "1.1",
    epic: "EPIC 1: User Authentication and Account Management",
    fullTitleHeader: "User Story 1.1: User Registration",
    specificTitle: "Implement user registration functionality",
    description:
      "As a customer, I want to create an account so that I can save my shopping preferences and track orders.",
    acceptanceCriteria: [
      "Registration form with email, password, name fields",
      "Email verification process",
      "Password strength requirements",
      "Success/error notifications",
    ],
    estimation: 3,
    image: "registration.png",
    isBacklog: false,
    rawContent: `### User Story 1.1: User Registration  ![registration](registration.png)  **Title**: Implement user registration functionality  **Description**: As a customer, I want to create an account so that I can save my shopping preferences and track orders.  **Acceptance Criteria**:  - Registration form with email, password, name fields  - Email verification process  - Password strength requirements  - Success/error notifications  > **Estimation**: 3 points`,
  },
  {
    id: "1.2",
    epic: "EPIC 1: User Authentication and Account Management",
    fullTitleHeader: "User Story 1.2: User Login",
    specificTitle: "Implement user login functionality",
    description:
      "As a registered user, I want to securely log into my account to access personalized features.",
    acceptanceCriteria: [
      "Login form with email/password",
      "Remember me option",
      "Proper error handling for invalid credentials",
      "Secure session management",
    ],
    estimation: 2,
    image: "login.png",
    isBacklog: false,
    rawContent: `### User Story 1.2: User Login  ![login](login.png)  **Title**: Implement user login functionality  **Description**: As a registered user, I want to securely log into my account to access personalized features.  **Acceptance Criteria**:  - Login form with email/password  - Remember me option  - Proper error handling for invalid credentials  - Secure session management  > **Estimation**: 2 points`,
  },
  {
    id: "1.3",
    epic: "EPIC 1: User Authentication and Account Management",
    fullTitleHeader: "User Story 1.3: Profile Management",
    specificTitle: "Create user profile management",
    description:
      "As a registered user, I want to view and edit my profile information to keep it up to date.",
    acceptanceCriteria: [
      "Profile page with user details",
      "Form to update personal information",
      "Password change functionality",
      "Address book management",
    ],
    estimation: 3,
    image: "profile.png",
    isBacklog: false,
    rawContent: `### User Story 1.3: Profile Management  ![profile](profile.png)  **Title**: Create user profile management  **Description**: As a registered user, I want to view and edit my profile information to keep it up to date.  **Acceptance Criteria**:  - Profile page with user details  - Form to update personal information  - Password change functionality  - Address book management  > **Estimation**: 3 points`,
  },
  {
    id: "1.4",
    epic: "EPIC 1: User Authentication and Account Management",
    fullTitleHeader: "User Story 1.4: Password Recovery",
    specificTitle: "Implement password recovery system",
    description:
      "As a user, I want to reset my password if I forget it so that I can regain access to my account.",
    acceptanceCriteria: [
      "Forgot password form",
      "Email with reset link",
      "Secure reset token handling",
      "Password reset form with validation",
    ],
    estimation: 3,
    image: "forgot-password.png",
    isBacklog: false,
    rawContent: `### User Story 1.4: Password Recovery  ![forgot-password](forgot-password.png)  **Title**: Implement password recovery system  **Description**: As a user, I want to reset my password if I forget it so that I can regain access to my account.  **Acceptance Criteria**:  - Forgot password form  - Email with reset link  - Secure reset token handling  - Password reset form with validation  > **Estimation**: 3 points`,
  },
  {
    id: "2.1",
    epic: "EPIC 2: Product Catalog and Browsing",
    fullTitleHeader: "User Story 2.1: Product Listing Page",
    specificTitle: "Implement product listing with filtering and sorting",
    description:
      "As a customer, I want to browse products with filtering and sorting options to find items easily.",
    acceptanceCriteria: [
      "Grid and list view options",
      "Pagination controls",
      "Sort by price, popularity, newest",
      "Filter by price range, category, attributes",
      "Loading states and empty states",
    ],
    estimation: 5,
    image: "product-listing.png",
    isBacklog: false,
    rawContent: `### User Story 2.1: Product Listing Page  ![product-listing](product-listing.png)  **Title**: Implement product listing with filtering and sorting  **Description**: As a customer, I want to browse products with filtering and sorting options to find items easily.  **Acceptance Criteria**:  - Grid and list view options  - Pagination controls  - Sort by price, popularity, newest  - Filter by price range, category, attributes  - Loading states and empty states  > **Estimation**: 5 points`,
  },
  {
    id: "2.2",
    epic: "EPIC 2: Product Catalog and Browsing",
    fullTitleHeader: "User Story 2.2: Product Details Page",
    specificTitle: "Create detailed product view",
    description:
      "As a customer, I want to see detailed information about products to make informed purchase decisions.",
    acceptanceCriteria: [
      "Multiple product images with gallery view",
      "Complete product information",
      "Add to cart functionality",
    ],
    estimation: 5,
    image: "product-details.png",
    isBacklog: false,
    rawContent: `### User Story 2.2: Product Details Page  ![product-details](product-details.png)  **Title**: Create detailed product view  **Description**: As a customer, I want to see detailed information about products to make informed purchase decisions.  **Acceptance Criteria**:  - Multiple product images with gallery view  - Complete product information  - Add to cart functionality  > **Estimation**: 5 points`,
  },
  {
    id: "2.3",
    epic: "EPIC 2: Product Catalog and Browsing",
    fullTitleHeader: "User Story 2.3: Category Navigation",
    specificTitle: "Implement category browsing functionality",
    description:
      "As a customer, I want to navigate through product categories and subcategories to find products.",
    acceptanceCriteria: [
      "Hierarchical category structure",
      "Category listing page",
      "Category-specific product pages",
    ],
    estimation: 3,
    image: "categories.png",
    isBacklog: false,
    rawContent: `### User Story 2.3: Category Navigation  ![categories](categories.png)  **Title**: Implement category browsing functionality  **Description**: As a customer, I want to navigate through product categories and subcategories to find products.  **Acceptance Criteria**:  - Hierarchical category structure  - Category listing page  - Category-specific product pages  > **Estimation**: 3 points`,
  },
  {
    id: "2.4",
    epic: "EPIC 2: Product Catalog and Browsing",
    fullTitleHeader: "User Story 2.4: Search Functionality",
    specificTitle: "Create product search system",
    description:
      "As a customer, I want to search for products by name, description, or keywords.",
    acceptanceCriteria: [
      "Search bar in header",
      "Search results page with filtering options",
      "Highlighting search terms in results",
      "Search suggestions",
      "No results handling",
    ],
    estimation: 5,
    image: "search.png",
    isBacklog: false,
    rawContent: `### User Story 2.4: Search Functionality  ![search](search.png)  **Title**: Create product search system  **Description**: As a customer, I want to search for products by name, description, or keywords.  **Acceptance Criteria**:  - Search bar in header  - Search results page with filtering options  - Highlighting search terms in results  - Search suggestions  - No results handling  > **Estimation**: 5 points`,
  },
  {
    id: "2.5",
    epic: "EPIC 2: Product Catalog and Browsing",
    fullTitleHeader: "User Story 2.5: Featured Products",
    specificTitle: "Implement featured products on homepage",
    description:
      "As a store owner, I want to highlight specific products on the homepage to increase visibility.",
    acceptanceCriteria: [
      "Featured product carousel/grid on homepage",
      "Admin interface to select featured products",
      "Responsive design for all screen sizes",
    ],
    estimation: 2,
    image: "featured.png",
    isBacklog: false,
    rawContent: `### User Story 2.5: Featured Products  ![featured](featured.png)  **Title**: Implement featured products on homepage  **Description**: As a store owner, I want to highlight specific products on the homepage to increase visibility.  **Acceptance Criteria**:  - Featured product carousel/grid on homepage  - Admin interface to select featured products  - Responsive design for all screen sizes  > **Estimation**: 2 points`,
  },
  {
    id: "3.1",
    epic: "EPIC 3: Shopping Cart and Checkout",
    fullTitleHeader: "User Story 3.1: Add to Cart Functionality",
    specificTitle: "Create add to cart system",
    description:
      "As a customer, I want to add products to my cart so I can prepare to purchase them.",
    acceptanceCriteria: [
      "Add to cart button on product pages and listings",
      "Quantity selection",
      "Success notification",
      "Cart icon update with count",
      "Inventory validation",
    ],
    estimation: 3,
    image: "add-to-cart.png",
    isBacklog: false,
    rawContent: `### User Story 3.1: Add to Cart Functionality  ![add-to-cart](add-to-cart.png)  **Title**: Create add to cart system  **Description**: As a customer, I want to add products to my cart so I can prepare to purchase them.  **Acceptance Criteria**:  - Add to cart button on product pages and listings  - Quantity selection  - Success notification  - Cart icon update with count  - Inventory validation  > **Estimation**: 3 points`,
  },
  {
    id: "3.2",
    epic: "EPIC 3: Shopping Cart and Checkout",
    fullTitleHeader: "User Story 3.2: Cart Management",
    specificTitle: "Implement shopping cart page",
    description:
      "As a customer, I want to see all items in my cart, modify quantities, and remove items.",
    acceptanceCriteria: [
      "List of cart items with images and details",
      "Quantity adjustment controls",
      "Remove item buttons",
      "Price calculations (subtotal, tax estimates)",
      "Empty cart state",
    ],
    estimation: 5,
    image: "cart-management.png",
    isBacklog: false,
    rawContent: `### User Story 3.2: Cart Management  ![cart-management](cart-management.png)  **Title**: Implement shopping cart page  **Description**: As a customer, I want to see all items in my cart, modify quantities, and remove items.  **Acceptance Criteria**:  - List of cart items with images and details  - Quantity adjustment controls  - Remove item buttons  - Price calculations (subtotal, tax estimates)  - Empty cart state  > **Estimation**: 5 points`,
  },
  {
    id: "3.3",
    epic: "EPIC 3: Shopping Cart and Checkout",
    fullTitleHeader: "User Story 3.3: Checkout Process",
    specificTitle: "Create multi-step checkout process",
    description:
      "As a customer, I want a clear checkout process to complete my purchase efficiently.",
    acceptanceCriteria: [
      "Multi-step checkout (shipping, billing, review)",
      "Guest checkout option",
      "Address form with validation",
      "Order summary throughout process",
      "Breadcrumb navigation between steps",
    ],
    estimation: 5,
    image: "checkout.png",
    isBacklog: false,
    rawContent: `### User Story 3.3: Checkout Process  ![checkout](checkout.png)  **Title**: Create multi-step checkout process  **Description**: As a customer, I want a clear checkout process to complete my purchase efficiently.  **Acceptance Criteria**:  - Multi-step checkout (shipping, billing, review)  - Guest checkout option  - Address form with validation  - Order summary throughout process  - Breadcrumb navigation between steps  > **Estimation**: 5 points`,
  },
  {
    id: "3.4",
    epic: "EPIC 3: Shopping Cart and Checkout",
    fullTitleHeader: "User Story 3.4: Order Confirmation",
    specificTitle: "Implement order confirmation process",
    description:
      "As a customer, I want confirmation of my order with details after checkout.",
    acceptanceCriteria: [
      "Order confirmation page with details",
      "Email confirmation",
      "Order tracking link",
      "Continue shopping button",
    ],
    estimation: 2,
    image: "order-confirmation.png",
    isBacklog: false,
    rawContent: `### User Story 3.4: Order Confirmation  ![order-confirmation](order-confirmation.png)  **Title**: Implement order confirmation process  **Description**: As a customer, I want confirmation of my order with details after checkout.  **Acceptance Criteria**:  - Order confirmation page with details  - Email confirmation  - Order tracking link  - Continue shopping button  > **Estimation**: 2 points`,
  },
  {
    id: "4.1",
    epic: "EPIC 4: Admin Product Management",
    fullTitleHeader: "User Story 4.1: Product CRUD",
    specificTitle:
      "Implement product creation, reading, updating, and deletion",
    description:
      "As an admin, I want to manage product listings to keep the catalog up to date.",
    acceptanceCriteria: [
      "Product listing page with filtering and sorting",
      "Add new product form with validation",
      "Edit product form pre-filled with existing data",
      "Delete product with confirmation",
      "Bulk actions for multiple products",
    ],
    estimation: 5,
    image: "product-manage.png",
    isBacklog: false,
    rawContent: `### User Story 4.1: Product CRUD   ![product-manage](product-manage.png)  ![product-create](product-create.png)  **Title**: Implement product creation, reading, updating, and deletion  **Description**: As an admin, I want to manage product listings to keep the catalog up to date.  **Acceptance Criteria**:  - Product listing page with filtering and sorting  - Add new product form with validation  - Edit product form pre-filled with existing data  - Delete product with confirmation  - Bulk actions for multiple products  > **Estimation**: 5 points`,
  },
  {
    id: "4.2",
    epic: "EPIC 4: Admin Product Management",
    fullTitleHeader: "User Story 4.2: Product Image Management",
    specificTitle: "Create product image upload and management",
    description:
      "As an admin, I want to upload and manage multiple images for each product.",
    acceptanceCriteria: [
      "Multiple image upload interface",
      "Image preview and reordering",
      "Primary image selection",
      "Delete image functionality",
      "Image optimization handling",
    ],
    estimation: 5,
    image: "product-image.png",
    isBacklog: false,
    rawContent: `### User Story 4.2: Product Image Management  ![product-image](product-image.png)  **Title**: Create product image upload and management  **Description**: As an admin, I want to upload and manage multiple images for each product.  **Acceptance Criteria**:  - Multiple image upload interface  - Image preview and reordering  - Primary image selection  - Delete image functionality  - Image optimization handling  > **Estimation**: 5 points`,
  },
  {
    id: "4.3",
    epic: "EPIC 4: Admin Product Management",
    fullTitleHeader: "User Story 4.3: Inventory Management",
    specificTitle: "Implement inventory tracking system",
    description:
      "As an admin, I want to track product inventory levels and receive alerts for low stock.",
    acceptanceCriteria: [
      "Inventory fields in product form",
      "SKU management",
      "Low stock threshold settings",
      "Inventory history logging",
      "Out of stock handling for front-end",
    ],
    estimation: 5,
    image: "inventory.png",
    isBacklog: false,
    rawContent: `### User Story 4.3: Inventory Management  ![inventory](inventory.png)  **Title**: Implement inventory tracking system  **Description**: As an admin, I want to track product inventory levels and receive alerts for low stock.  **Acceptance Criteria**:  - Inventory fields in product form  - SKU management  - Low stock threshold settings  - Inventory history logging  - Out of stock handling for front-end  > **Estimation**: 5 points`,
  },
  {
    id: "5.1",
    epic: "EPIC 5: Admin Category Management",
    fullTitleHeader: "User Story 5.1: Category CRUD",
    specificTitle: "Create category management functionality",
    description:
      "As an admin, I want to create, update, and delete product categories to organize the catalog effectively.",
    acceptanceCriteria: [
      "Category listing with hierarchical view",
      "Add new category form with parent selection",
      "Edit category form",
      "Delete category with validation for associated products",
      "Reordering of categories",
    ],
    estimation: 5,
    image: "category-listing.png",
    isBacklog: false,
    rawContent: `### User Story 5.1: Category CRUD  ![category-listing](category-listing.png)  ![catogory-create](catogory-create.png)  **Title**: Create category management functionality  **Description**: As an admin, I want to create, update, and delete product categories to organize the catalog effectively.  **Acceptance Criteria**:  - Category listing with hierarchical view  - Add new category form with parent selection  - Edit category form  - Delete category with validation for associated products  - Reordering of categories  > **Estimation**: 5 points`,
  },
  {
    id: "5.2",
    epic: "EPIC 5: Admin Category Management",
    fullTitleHeader: "User Story 5.2: Hierarchical Category Structure",
    specificTitle: "Implement nested category system",
    description:
      "As an admin, I want to organize categories in a hierarchical structure with main categories and subcategories.",
    acceptanceCriteria: [
      "Visual representation of category hierarchy",
      "Ability to nest categories up to 3 levels",
      "Parent-child relationship management",
      "Validation to prevent circular references",
    ],
    estimation: 5,
    image: null,
    isBacklog: false,
    rawContent: `### User Story 5.2: Hierarchical Category Structure  **Title**: Implement nested category system  **Description**: As an admin, I want to organize categories in a hierarchical structure with main categories and subcategories.  **Acceptance Criteria**:  - Visual representation of category hierarchy  - Ability to nest categories up to 3 levels  - Parent-child relationship management  - Validation to prevent circular references  > **Estimation**: 5 points`,
  },
  {
    id: "5.3",
    epic: "EPIC 5: Admin Category Management",
    fullTitleHeader: "User Story 5.3: Category Image Management",
    specificTitle: "Add category image setup functionality",
    description:
      "As an admin, I want to add images to categories for better visual representation.",
    acceptanceCriteria: [
      "Image setup for categories",
      "Image preview",
      "Default image for categories without custom images",
    ],
    estimation: 2,
    image: "category-image.png",
    isBacklog: false,
    rawContent: `### User Story 5.3: Category Image Management  ![category-image](category-image.png)  **Title**: Add category image setup functionality  **Description**: As an admin, I want to add images to categories for better visual representation.  **Acceptance Criteria**:  - Image setup for categories  - Image preview  - Default image for categories without custom images  > **Estimation**: 2 points`,
  },
  {
    id: "6.1",
    epic: "EPIC 6: Order Management",
    fullTitleHeader: "User Story 6.1: Order Listing and Filtering",
    specificTitle: "Implement order list with advanced filtering",
    description:
      "As an admin, I want to view and filter all orders to efficiently manage customer purchases.",
    acceptanceCriteria: [
      "Order list with key details",
      "Filtering by date, status, customer, amount",
      "Sorting options",
      "Pagination for large order volumes",
    ],
    estimation: 3,
    image: "order-listing.png",
    isBacklog: false,
    rawContent: `### User Story 6.1: Order Listing and Filtering  ![order-listing](order-listing.png)  **Title**: Implement order list with advanced filtering  **Description**: As an admin, I want to view and filter all orders to efficiently manage customer purchases.  **Acceptance Criteria**:  - Order list with key details  - Filtering by date, status, customer, amount  - Sorting options  - Pagination for large order volumes  > **Estimation**: 3 points`,
  },
  {
    id: "6.2",
    epic: "EPIC 6: Order Management",
    fullTitleHeader: "User Story 6.2: Order Details View",
    specificTitle: "Create detailed order view",
    description:
      "As an admin, I want to see complete order details to process orders correctly.",
    acceptanceCriteria: [
      "Customer information",
      "Complete list of ordered items",
      "Payment information",
      "Shipping details",
      "Order notes",
      "Order history log",
    ],
    estimation: 5,
    image: "order-details.png",
    isBacklog: false,
    rawContent: `### User Story 6.2: Order Details View  ![order-details](order-details.png)  **Title**: Create detailed order view  **Description**: As an admin, I want to see complete order details to process orders correctly.  **Acceptance Criteria**:  - Customer information  - Complete list of ordered items  - Payment information  - Shipping details  - Order notes  - Order history log  > **Estimation**: 5 points`,
  },
  {
    id: "6.3",
    epic: "EPIC 6: Order Management",
    fullTitleHeader: "User Story 6.3: Order Status Management",
    specificTitle: "Implement order status updates",
    description:
      "As an admin, I want to update order status as it moves through the fulfillment process.",
    acceptanceCriteria: [
      "Status change dropdown",
      "Automated emails for status changes",
      "Status history tracking",
    ],
    estimation: 2,
    image: "order-status.png",
    isBacklog: false,
    rawContent: `### User Story 6.3: Order Status Management  ![order-status](order-status.png)  **Title**: Implement order status updates  **Description**: As an admin, I want to update order status as it moves through the fulfillment process.  **Acceptance Criteria**:  - Status change dropdown  - Automated emails for status changes  - Status history tracking  > **Estimation**: 2 points`,
  },
  {
    id: "6.4",
    epic: "EPIC 6: Order Management",
    fullTitleHeader: "User Story 6.4: Invoice Generation",
    specificTitle: "Create invoice generation functionality",
    description:
      "As an admin, I want to generate and send invoices for orders.",
    acceptanceCriteria: [
      "PDF invoice generation",
      "Email invoice functionality",
      "Download invoice option",
      "Invoice template customization",
    ],
    estimation: 5,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 6.4: Invoice Generation  **Title**: Create invoice generation functionality  **Description**: As an admin, I want to generate and send invoices for orders.  **Acceptance Criteria**:  - PDF invoice generation  - Email invoice functionality  - Download invoice option  - Invoice template customization  > **Estimation**: 5 points`,
  },

  {
    id: "7.1",
    epic: "EPIC 7: Customer Support System",
    fullTitleHeader: "User Story 7.1: FAQ System",
    specificTitle: "Implement FAQ knowledge base",
    description:
      "As a store owner, I want to provide frequently asked questions to reduce support inquiries.",
    acceptanceCriteria: [
      "Categorized FAQ entries",
      "Search functionality",
      "Admin interface to add/edit FAQs",
      "Structured layout with expand/collapse",
    ],
    estimation: 2,
    image: "faq.png",
    isBacklog: false,
    rawContent: `### User Story 7.1: FAQ System  ![faq](faq.png)  **Title**: Implement FAQ knowledge base  **Description**: As a store owner, I want to provide frequently asked questions to reduce support inquiries.  **Acceptance Criteria**:  - Categorized FAQ entries  - Search functionality  - Admin interface to add/edit FAQs  - Structured layout with expand/collapse  > **Estimation**: 2 points`,
  },
  {
    id: "7.2",
    epic: "EPIC 7: Customer Support System",
    fullTitleHeader: "User Story 7.2: Contact Form",
    specificTitle: "Create contact page with form submission",
    description:
      "As a customer, I want to contact the store with questions or issues.",
    acceptanceCriteria: [
      "Contact form with fields for name, email, subject, message",
      "Form validation",
      "Success/error notifications",
      "Email notification to administrators",
    ],
    estimation: 2,
    image: "contact-page.png",
    isBacklog: false,
    rawContent: `### User Story 7.2: Contact Form  ![contact-page](contact-page.png)  **Title**: Create contact page with form submission  **Description**: As a customer, I want to contact the store with questions or issues.  **Acceptance Criteria**:  - Contact form with fields for name, email, subject, message  - Form validation  - Success/error notifications  - Email notification to administrators  > **Estimation**: 2 points`,
  },
  {
    id: "7.3",
    epic: "EPIC 7: Customer Support System",
    fullTitleHeader: "User Story 7.3: Support Ticket System",
    specificTitle: "Implement support ticket management",
    description:
      "As a customer, I want to submit support tickets and track their status.",
    acceptanceCriteria: [
      "Ticket submission form",
      "Ticket listing in customer account",
      "Status updates and communication thread",
      "File attachment capability",
    ],
    estimation: 5,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 7.3: Support Ticket System  **Title**: Implement support ticket management  **Description**: As a customer, I want to submit support tickets and track their status.  **Acceptance Criteria**:  - Ticket submission form  - Ticket listing in customer account  - Status updates and communication thread  - File attachment capability  > **Estimation**: 5 points`,
  },
  {
    id: "7.4",
    epic: "EPIC 7: Customer Support System",
    fullTitleHeader: "User Story 7.4: Admin Ticket Management",
    specificTitle: "Create admin interface for ticket handling",
    description:
      "As an admin, I want to manage customer support tickets efficiently.",
    acceptanceCriteria: [
      "Ticket listing with filtering and sorting",
      "Ticket assignment to staff members",
      "Response interface with templates",
      "Status change and resolution tracking",
      "Internal notes for staff only",
    ],
    estimation: 5,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 7.4: Admin Ticket Management  **Title**: Create admin interface for ticket handling  **Description**: As an admin, I want to manage customer support tickets efficiently.  **Acceptance Criteria**:  - Ticket listing with filtering and sorting  - Ticket assignment to staff members  - Response interface with templates  - Status change and resolution tracking  - Internal notes for staff only  > **Estimation**: 5 points`,
  },
  {
    id: "8.1",
    epic: "EPIC 8: Promotions and Marketing",
    fullTitleHeader: "User Story 8.1: About Page",
    specificTitle: "Create company about page",
    description:
      "As a store owner, I want to share company information and story with customers.",
    acceptanceCriteria: [
      "Editable about page sections",
      "Team member profiles",
      "Company history timeline",
      "Mission and values statements",
    ],
    estimation: 2,
    image: "about.png",
    isBacklog: false,
    rawContent: `### User Story 8.1: About Page ![about](about.png)  **Title**: Create company about page  **Description**: As a store owner, I want to share company information and story with customers.  **Acceptance Criteria**: - Editable about page sections - Team member profiles - Company history timeline - Mission and values statements > **Estimation**: 2 points`,
  },,
  {
    id: "8.2",
    epic: "EPIC 8: Promotions and Marketing",
    fullTitleHeader: "User Story 8.2: Featured Products Management",
    specificTitle: "Create featured products selection tool",
    description:
      "As an admin, I want to select which products appear as featured on the homepage.",
    acceptanceCriteria: [
      "Product selection interface",
      "Ordering control for featured products",
      "Scheduling of featured periods",
    ],
    estimation: 2,
    image: "featured.png",
    isBacklog: false,
    rawContent: `### User Story 8.2: Featured Products Management  ![featured](featured.png)  **Title**: Create featured products selection tool  **Description**: As an admin, I want to select which products appear as featured on the homepage.  **Acceptance Criteria**:  - Product selection interface  - Ordering control for featured products  - Scheduling of featured periods  > **Estimation**: 2 points`,
  },
  {
    id: "8.3",
    epic: "EPIC 8: Promotions and Marketing",
    fullTitleHeader: "User Story 8.3: Related Products",
    specificTitle: "Create related products functionality",
    description:
      "As an admin, I want to specify related products to increase cross-selling opportunities.",
    acceptanceCriteria: [
      "Related product selection in product form",
      "Automatic suggestions based on category",
      "Display of related products on product page",
    ],
    estimation: 2,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 8.3: Related Products  **Title**: Create related products functionality  **Description**: As an admin, I want to specify related products to increase cross-selling opportunities.  **Acceptance Criteria**:  - Related product selection in product form  - Automatic suggestions based on category  - Display of related products on product page  > **Estimation**: 2 points`,
  },
  {
    id: "9.1",
    epic: "EPIC 9: Analytics and Reporting",
    fullTitleHeader: "User Story 9.1: Sales Dashboard",
    specificTitle: "Create admin sales dashboard",
    description:
      "As an admin, I want a dashboard with key sales metrics to track business performance.",
    acceptanceCriteria: [
      "Summary of recent sales",
      "Charts for daily/weekly/monthly sales",
      "Top selling products",
      "Revenue trends",
      "Filters for date ranges",
    ],
    estimation: 5,
    image: "sale-dashboard.png",
    isBacklog: false,
    rawContent: `### User Story 9.1: Sales Dashboard  ![sale-dashboard](sale-dashboard.png)  **Title**: Create admin sales dashboard  **Description**: As an admin, I want a dashboard with key sales metrics to track business performance.  **Acceptance Criteria**: - Summary of recent sales - Charts for daily/weekly/monthly sales - Top selling products - Revenue trends - Filters for date ranges  > **Estimation**: 5 points`,
  },
  {
    id: "9.2",
    epic: "EPIC 9: Analytics and Reporting",
    fullTitleHeader: "User Story 9.2: Inventory Reports",
    specificTitle: "Implement inventory reporting",
    description:
      "As an admin, I want inventory reports to manage stock levels.",
    acceptanceCriteria: [
      "Low stock alerts",
      "Out of stock reports",
      "Inventory value calculations",
      "Movement history for products",
    ],
    estimation: 3,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 9.2: Inventory Reports **Title**: Implement inventory reporting **Description**: As an admin, I want inventory reports to manage stock levels. **Acceptance Criteria**: - Low stock alerts - Out of stock reports - Inventory value calculations - Movement history for products > **Estimation**: 3 points`,
  },
  {
    id: "9.3",
    epic: "EPIC 9: Analytics and Reporting",
    fullTitleHeader: "User Story 9.3: Export Reports",
    specificTitle: "Implement report export functionality",
    description: "As an admin, I want to export reports for further analysis.",
    acceptanceCriteria: [
      "CSV and PDF export options",
      "Customizable export fields",
      "Scheduled automatic exports",
    ],
    estimation: 2,
    image: null,
    isBacklog: true,
    rawContent: `### User Story 9.3: Export Reports **Title**: Implement report export functionality **Description**: As an admin, I want to export reports for further analysis. **Acceptance Criteria**: - CSV and PDF export options - Customizable export fields - Scheduled automatic exports > **Estimation**: 2 points`,
  },
];
